name: Node CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10.15.3']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, and test
      run: |
        yarn install --frozen-lockfile
        yarn test
      env:
        CI: true
